### ISSUE TITLE
roadmap to v1.0.0?

### ISSUE THREAD

**Issue by rursprung** [rust-embedded-community/hash32#17]
do you have a roadmap to releasing a v1.0.0? it would be cool if you could create the tickets for what you think is missing for v1.0.0 and assign them to a v1.0.0 milestone.

rationale: theoretically, one should only build on released software, so using 0.x pre-releases for production software isn't looked on too well. in the rust eco-system there are sadly a lot of crates which stay on 0.x for years but are heavily used. having a roadmap helps in understanding why a crate is not yet released as 1.x (or higher) and allows analysing the trade-offs (is it acceptable to use the crate in production even though these features are missing?).

furthermore, this would help with contributors: they know where work still needs to be done and they can offer their help focused on these topics.

specifically this seems to block the `heapless` crate from releasing an 1.0.0 release: https://github.com/rust-embedded/heapless/issues/410#issuecomment-1810755645

with over 9 million downloads the `hash32` crate is heavily used in the (embedded) rust ecosystem (see also the [dependent crates](https://crates.io/crates/hash32/reverse_dependencies), primarily through `heapless`) and having a stable release would be beneficial for all of them.

this crate seems to be very stable (no open issues, only one open PR, no commits since a year), indicating that it'd be a good candidate for an 1.0.0 release (either just re-release the last release as 1.0.0 or optionally include some cleanups along with it if needed).

**Comment by newAM** [comment]
Similar to heapless 1.0 I would like to go through a checklist: https://github.com/rust-embedded/heapless/issues/535

I'm very busy with work recently, but I'll try to get started this week. I don't expect this to take long, as mentioned this crate is very stable without a lot of activity.

# Checklist

- [x] Review allowed warnings and clippy lints
  - #31
  - https://github.com/rust-embedded-community/hash32/blob/a49d0a4e992766b9e29075c40eeb60be594694b4/src/murmur3.rs#L211
- [x] Review non-default clippy lints (`-W clippy::pedantic -W clippy::nursery`)
  - #26
- [x] Review explicit panics, unwraps, expects in non-test code
- [x] Review crate features
- [x] grep for `fixme`, `todo`, `xxx`, ect.
  - https://github.com/rust-embedded-community/hash32/blob/a49d0a4e992766b9e29075c40eeb60be594694b4/src/murmur3.rs#L189
  - #40
- [x] Review open issues
- [x] Review open pull-requests
- [x] Improve test coverage
  - #24
  - #25

# [Rust API Guidelines Checklist](https://rust-lang.github.io/api-guidelines/checklist.html#rust-api-guidelines-checklist)

- **Naming** *(crate aligns with Rust naming conventions)*
  - [x] Casing conforms to RFC 430 (C-CASE)
  - [x] Ad-hoc conversions follow `as_`, `to_`, `into_` conventions (C-CONV)
  - [x] Getter names follow Rust convention (C-GETTER)
  - [x] Methods on collections that produce iterators follow `iter`, `iter_mut`, `into_iter` (C-ITER)
  - [x] Iterator type names match the methods that produce them (C-ITER-TY)
  - [x] Feature names are free of placeholder words (C-FEATURE)
  - [x] Names use a consistent word order (C-WORD-ORDER)
- **Interoperability** *(crate interacts nicely with other library functionality)*
  - [x] Types eagerly implement common traits (C-COMMON-TRAITS)
    - `Copy`, `Clone`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Hash`, `Debug`,
      `Display`, `Default`
    - `std::hash::DefaultHasher` implements `Debug` and `Clone`.
    - #39
  - [x] Conversions use the standard traits `From`, `AsRef`, `AsMut` (C-CONV-TRAITS)
  - [x] Collections implement `FromIterator` and `Extend` (C-COLLECT)
  - [x] Data structures implement Serde's `Serialize`, `Deserialize` (C-SERDE)
  - [x] Types are `Send` and `Sync` where possible (C-SEND-SYNC)
  - [x] Error types are meaningful and well-behaved (C-GOOD-ERR)
  - [x] Binary number types provide `Hex`, `Octal`, `Binary` formatting (C-NUM-FMT)
  - [x] Generic reader/writer functions take `R: Read` and `W: Write` by value (C-RW-VALUE)
- **Macros** *(crate presents well-behaved macros)*
  - [x] Input syntax is evocative of the output (C-EVOCATIVE)
  - [x] Macros compose well with attributes (C-MACRO-ATTR)
  - [x] Item macros work anywhere that items are allowed (C-ANYWHERE)
  - [x] Item macros support visibility specifiers (C-MACRO-VIS)
  - [x] Type fragments are flexible (C-MACRO-TY)
- **Documentation** *(crate is abundantly documented)*
  - [x] Crate level docs are thorough and include examples (C-CRATE-DOC)
    - #38
  - [x] All items have a rustdoc example (C-EXAMPLE)
    - #35
    - #37
  - [x] Examples use `?`, not `try!`, not `unwrap` (C-QUESTION-MARK)
  - [x] Function docs include error, panic, and safety considerations (C-FAILURE)
  - [x] Prose contains hyperlinks to relevant things (C-LINK)
  - [x] Cargo.toml includes all common metadata (C-METADATA)
    - authors, description, license, homepage, documentation, repository,
      keywords, categories
  - [x] Release notes document all significant changes (C-RELNOTES)
    - #33
  - [x] Rustdoc does not show unhelpful implementation details (C-HIDDEN)
- **Predictability** *(crate enables legible code that acts how it looks)*
  - [x] Smart pointers do not add inherent methods (C-SMART-PTR)
  - [x] Conversions live on the most specific type involved (C-CONV-SPECIFIC)
  - [x] Functions with a clear receiver are methods (C-METHOD)
  - [x] Functions do not take out-parameters (C-NO-OUT)
  - [x] Operator overloads are unsurprising (C-OVERLOAD)
  - [x] Only smart pointers implement `Deref` and `DerefMut` (C-DEREF)
  - [x] Constructors are static, inherent methods (C-CTOR)
- **Flexibility** *(crate supports diverse real-world use cases)*
  - [x] Functions expose intermediate results to avoid duplicate work (C-INTERMEDIATE)
  - [x] Caller decides where to copy and place data (C-CALLER-CONTROL)
  - [x] Functions minimize assumptions about parameters by using generics (C-GENERIC)
  - [x] Traits are object-safe if they may be useful as a trait object (C-OBJECT)
- **Type safety** *(crate leverages the type system effectively)*
  - [x] Newtypes provide static distinctions (C-NEWTYPE)
  - [x] Arguments convey meaning through types, not `bool` or `Option` (C-CUSTOM-TYPE)
  - [x] Types for a set of flags are `bitflags`, not enums (C-BITFLAG)
  - [x] Builders enable construction of complex values (C-BUILDER)
- **Dependability** *(crate is unlikely to do the wrong thing)*
  - [x] Functions validate their arguments (C-VALIDATE)
  - [x] Destructors never fail (C-DTOR-FAIL)
  - [x] Destructors that may block have alternatives (C-DTOR-BLOCK)
- **Debuggability** *(crate is conducive to easy debugging)*
  - [x] All public types implement `Debug` (C-DEBUG)
    - #39
  - [x] `Debug` representation is never empty (C-DEBUG-NONEMPTY)
- **Future proofing** *(crate is free to improve without breaking users' code)*
  - [x] Sealed traits protect against downstream implementations (C-SEALED)
  - [x] Structs have private fields (C-STRUCT-PRIVATE)
  - [x] Newtypes encapsulate implementation details (C-NEWTYPE-HIDE)
  - [x] Data structures do not duplicate derived trait bounds (C-STRUCT-BOUNDS)
- **Necessities** *(to whom they matter, they really matter)*
  - [x] Public dependencies of a stable crate are stable (C-STABLE)
  - [x] Crate and its dependencies have a permissive license (C-PERMISSIVE)

# Dependencies

- [x] remove byteorder, #22

# Questions

- What should the MSRV policy look like?
  - I think [Ferrocene](https://ferrocene.dev/en/) support is important for some users, this is currently at 1.83.0
  - #18

**Comment by rursprung** [comment]
i'd add one more point to the checklist: add test coverage. currently there's 0 test coverage. i'd expect a 1.0 crate to come with a reasonable set of tests to ensure that there won't be any unexpected breakage in the future.

(note: i have no stake in this library and have never used it directly. i came across this because of `heapless`, which has it as a dependency and i was interested in that reaching 1.0)

**Comment by eldruin** [comment]
It is now [published](https://github.com/rust-embedded-community/hash32/releases/tag/v1.0.0)! Thank you everybody! 🎉
